### ISSUE TITLE
figure out how to expose `changes` of children

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-widgets-base#1]
Figure out how to expose changes in children of the aiida widgets so that one can `observe` the aiida widgets directly.

Note: Until this is fixed, one can still observe changes in the children but needs to know how they are stored internally (e.g. `StructureUploadWidget.btn_store`)

**Comment by yakutovicha** [comment]
Traitles might be a good candidate to look at: https://github.com/ipython/traitlets

**Comment by ltalirz** [comment]
Indeed, traitlets are the way to go.
For observing changes in variables of built-in types (e.g. a `dict`), this is all that is needed:

```python
from traitlets import Dict

class MyWidget(iwp.VBox):
   output_dict = Dict()
   ...

def my_callback(change):
    print("dict changed")

w = MyWidget()
w.observe(my_callback, names=['output_dict'])
```

Since the output of many of our widgets will be AiiDA nodes, we just need to figure out how to make a traitlet type for them (should not be too difficult).

**Comment by yakutovicha** [comment]
just not to forget:
https://traitlets.readthedocs.io/en/stable/using_traitlets.html#observe
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Custom.html#Making-the-widget-stateful

**Comment by yakutovicha** [comment]
I think we have already figured out, so I close the issue

**Comment by ltalirz** [comment]
We actually haven't figured out the last point I was mentioning.

See here for an example of how to write a custom traitlet type:
https://github.com/jupyter-widgets/traittypes/blob/609b402bcbf8dd3bc0ad4b0dd76fc32d68221871/traittypes/traittypes.py#L28
https://github.com/jupyter-widgets/traittypes/blob/609b402bcbf8dd3bc0ad4b0dd76fc32d68221871/traittypes/traittypes.py#L83

**Comment by yakutovicha** [comment]
> Since the output of many of our widgets will be AiiDA nodes, we just need to figure out how to make a traitlet type for them (should not be too difficult).

This can be achieved simply like this:
```
class MyClass(traitlets.HasTraits):
    structure =  traitlets.Instance(StructureData)
```
That means the structure will become a traitlet that accepts StructureData types only. One can observe this traitlet in the standard way:

```
a = MyClass()
a.observe(my_function, names='structure')
```

@ltalirz please close the issue or let me know if there are other open questions.

**Comment by ltalirz** [comment]
thanks, sounds good!
