### ISSUE TITLE
How to deal with more general cases?

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-widgets-base#123]
Many supercomputing centres are now requesting specific ssh protocols to generate ssh key and
they enforce usage of a password when generating the ssh key
How to deal with this? This can become soon a NO GO ITEM as it is at present for LRZ...

https://doku.lrz.de/display/PUBLIC/ssh+-+Secure+Shell+on+LRZ+HPC+Systems

https://github.com/aiidalab/aiidalab-widgets-base/blob/d7a25335d65daedf5dbd708a25a8f96de189841d/aiidalab_widgets_base/computers.py#L35

**Comment by yakutovicha** [comment]
@giovannipizzi can you please comment on this? I remember you were working on adding the possibility to AiiDA to deal with passphrases.

**Comment by giovannipizzi** [comment]
AiiDA can use a ssh agent to store the passphrase.
I had added docs here: https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/ssh.html#using-passphrase-protected-keys-via-an-ssh-agent

Please report if this works in AiiDA lab  (@yakutovicha , you might want to setup the script I describe in the docs inside AiiDA lab, to persist the agent across shells - and @cpignedoli please let us know if in your centres using a passphrase-protected key and using a ssh-agent would solve the issue).

**Comment by cpignedoli** [comment]
Excellent, thank you very much Giovanni.
I have an active account on superMUC at LRZ so I can test it !!

**Comment by yakutovicha** [comment]
Thanks, @giovannipizzi, we tested it and it seems to work perfectly!

It appears that ssh-agent isn't starting automatically on AiiDAlab. I will add it to the aiida-prerequisites image then.
