### ISSUE TITLE
Update functionality of Setup Computer and Setup Code

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab-widgets-base#13]
During PR #12, some functionality was found to not be useful for the notebooks that setup Computer and Code.

This issue represents the fact that these notebooks should perhaps be revisited and the functionality should possibly be updated, removed or additions should be made.

**Comment by yakutovicha** [comment]
While merging the PR I discovered a couple of changes that might be worth to consider:

1) Move `extract_sshcomputersetup_arguments` into `SshComputerSetup` class?
2) Move `extract_aiidacomputer_arguments` into `AiidaComputerSetup` class?
3) Move `extract_aiidacodesetup_arguments` into `AiiDACodeSetup` class?

**Comment by ltalirz** [comment]
why not?
just make it a class method, not an instance method.

**Comment by ltalirz** [comment]
hm... or maybe you were thinking of forwarding it to the instance directly?
up to you, happy to review

**Comment by yakutovicha** [comment]
Let's try to use widgets and collect the ideas from other people. If you encounter any problems or want to suggest something - just drop a line here.

Once we agree on further improvements - I am happy to implement them

**Comment by yakutovicha** [comment]
Since we didn't manage to collect ideas on what to improve/simplify I am going to close the issue. While fixing #21 a lot of things will be improved/get simpler.
