### ISSUE TITLE
Consider using the `black` formatter instead of `yapf` and `prospector`

### ISSUE THREAD

**Issue by CasperWA** [aiidalab/aiidalab-widgets-base#133]
(...)
On another note, I am not fond of the yapf styling. The "fix" is a rather ugly extra indentation. Also, we already moved away from `prospector` in `aiida-core` due to it being slow and causing some problems. I think mainly with its formatting choices and dependencies. Perhaps we should move to `black` instead?

_Originally posted by @CasperWA in https://github.com/aiidalab/aiidalab-widgets-base/pull/131#issuecomment-702035526_

**Comment by CasperWA** [comment]
[Here](https://black.readthedocs.io/en/stable/) is a link to the `black` formatter's documentation.

The main thing here is that it will turn all `str` to double-quotations. But this can be remedied by a small configuration file to simply avoid doing that "fix" if not desired.

**Comment by yakutovicha** [comment]
I have a more general question in this respect. Should we somehow formalize the formatting and use it across different packages. Originally, I just copied everything from the `aiida-core`, but I didn't put any thoughts on how actually we should shape the code.

**Comment by csadorf** [comment]
I agree with @CasperWA and would prefer to adopt `black` across all packages that we maintain. I recently did that for the qe-app: https://github.com/aiidalab/aiidalab-qe/commit/2dc64eeb0082e4dc849d5baaf7a8fbfcf3e5cb15

I think the best way to accomplish this is to update the app cookie cutter to directly incorporate the pre-commit configuration.

**Comment by yakutovicha** [comment]
fixed by #175
