### ISSUE TITLE
settings for minimum poll

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-widgets-base#141]
the configuration of a computer should have a default setting for minimum poll
so that a user does not need to do manually:

verdi computer configure ssh computer-name --safe-interval 120 -n

verdi shell
c=load_computer('computer_name')
c.set_minimum_job_poll_interval(120)

https://github.com/aiidalab/aiidalab-widgets-base/blob/efad328d0f83d099fdc529792201a946b48110fa/aiidalab_widgets_base/computers.py#L416

**Comment by yakutovicha** [comment]
@cpignedoli suggests to set it to 60.
