### ISSUE TITLE
Move useful wizard, process check widget from aiidalab-qe 

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-widgets-base#166]
There are some useful and general widgets of `aiidalab-qe` app such as:

1) Wizard App in https://github.com/aiidalab/aiidalab-qe/blob/master/wizard.py
2) process follower widgets in https://github.com/aiidalab/aiidalab-qe/blob/master/process.py and https://github.com/aiidalab/aiidalab-qe/blob/master/widgets.py . Some of them are duplicate with widgets in this app, such as `ProgressBarWidget`.

The widgets in above mentioned files are independent of the specific calculation plugin.
I think it is more clear to move them in here and make them reusable. Or maybe better to have an `aiidalab-widget-extend` to package the widgets that can be reused.

**Comment by yakutovicha** [comment]
In principle, I am in favour of moving general widgets here. @csadorf can you please share your opinion on this?

**Comment by csadorf** [comment]
> In principle, I am in favour of moving general widgets here. @csadorf can you please share your opinion on this?

Absolutely, the main reason that they are maintained as part of the QE app right now is because the dependency specification was previously not well established yet and because I simply didn't get to moving those widgets into aiidalab-widgets-base yet.

**Comment by csadorf** [comment]
I am currently going through another revision of the QE app. Once that is completed, I'll backport all general widgets etc. into aiidalab-widgets-base to address this issue.
