### ISSUE TITLE
Using the widgets without aiida instaltion

### ISSUE THREAD

**Issue by sandipde** [aiidalab/aiidalab-widgets-base#194]
Hi ! 
 I was trying to use the structures.ipynb on a computer that does not have aiida instalation and realised that is not possible as it tries to load aiida profile.  I am just trying to use the structure upload and edit part without any interaction to aiida for this case. I did manage to comment out some of the aiida import lines and create a fake profle  in ~/.aiida/config.json  that gets the widget running but still it crashes when I try to upload a cif file complaining about the nonexistent posgresql server. I was under the impression that these widgets are meant to be run on computers that not necessarily have aiida setup. Before I hack into the code, can you please tell me if it is not possible otherwise ? 
Thanks in advance. 
Best regards
Sandip

**Comment by yakutovicha** [comment]
hey @sandipde 

>  I was under the impression that these widgets are meant to be run on computers that not necessarily have aiida setup

Actually, the purpose of this repository is exactly the opposite. Most of the widgets are meant to work with AiiDA and provide a user-friendly interface to interact with it. For instance, the editor keeps the history of your edits in the aiida database. 

But, of course, you can extract the editor and reuse it for your purposes. However, this can't be done without hacking :)

**Comment by csadorf** [comment]
I think it is a valid point that we should strive to develop the widgets in a way that they don't create an *artificial* AiiDA-dependence where that is not necessary. However, this is the `aiidalab-widgets-base` library, so a dependence on AiiDA is generally expected.

**Comment by sandipde** [comment]
Thanks @yakutovicha  for your quick answer. @csadorf fair point. Thanks
