### ISSUE TITLE
migration towards aiida-1.0

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-widgets-base#20]
@CasperWA @yakutovicha I've started the migration towards aiida-1.0 in the branch [`aiida-1.0`](https://github.com/aiidalab/aiidalab-widgets-base/tree/aiida-1.0).

 * ran aiida-plugin-migrator.py
 * several adjustments to make at least the structure upload work (I can run the structure.ipynb notebook and upload an example structure. For some reason, the regular upload button does not show)
 * added .travis.yml
    I noticed that @yakutovicha did not use the `pre-commit` hooks, so there are [loads of linter issues](https://travis-ci.org/aiidalab/aiidalab-widgets-base/jobs/533905935#L874) in the new code. Please fix them at some point.

**Comment by yakutovicha** [comment]
The `pre-commit` issues are not all fixed. Migration is completed in the aiida-1.0 branch. Keeping the branch alive until aiida lab will be able to properly handle the package versions.
