### ISSUE TITLE
please update aiida registry

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-widgets-base#205]
see https://github.com/aiidateam/aiida-registry/runs/2614571830?check_suite_focus=true#step:7:118

**Comment by ltalirz** [comment]
@yakutovicha 
Just to clarify: this package is [registered on the AiiDA registry](https://aiidateam.github.io/aiida-registry/plugins/widgets.html)

In  https://github.com/aiidalab/aiidalab-widgets-base/commit/2dc5116d5a5d17298858306c1950c569b9a236be you removed the `setup.json` which the registry uses to parse information about the package.
I suggest you either remove this package from the registry or look into https://github.com/aiidateam/aiida-registry/issues/132

**Comment by yakutovicha** [comment]
@ltalirz, I think this package should be removed from the registry. Not sure what was the motivation behind adding it there.

@csadorf I see that you've assigned yourself. Are you going to remove the package from the registry?

**Comment by ltalirz** [comment]
I'll remove it, no problem
