### ISSUE TITLE
`StructureUploadWidget`: Provide better explanation or resource for supported formats

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-widgets-base#208]
When the user wants to understand what formats are supported for uploading with the `StructureUploadWidget`, they are directed to the source code of the `ase.io` package:

https://wiki.fysik.dtu.dk/ase/_modules/ase/io/formats.html

This isn't very insightful. Don't they have a page that lists the supported formats?

**Comment by yakutovicha** [comment]
fixed in #225.
