### ISSUE TITLE
Confusing package name

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-widgets-base#226]
In the [AiiDAlab app registry](https://aiidalab.github.io/aiidalab-registry/) and in the [aiidalab documentation](https://aiidalab.readthedocs.io/en/latest/app_development/widgets.html#aiidalab-base-widgets), the widgets are called "AiiDAlab Base Widgets".

In the documentation of this package, however, they are called "AiiDAlab Widgets Base" and abbreviated AWB:

![image](https://user-images.githubusercontent.com/1053245/132946986-0354f016-b3d5-4fe4-8186-36165e61f200.png)

This causes unnecessary confusion - we should just decide on a name an stick to it.

Mentioning @csadorf and @yakutovicha

**Comment by ltalirz** [comment]
In my view, the "base" pre/suffix is unnecessary (notabene: the ipywidgets are also not called "ipywidgets-base").

Since I am revising the AiiDAlab & widgets docs, I will be removing "base" from descriptions of the widgets and just refer to them as "AiiDAlab widgets".
If at some point in the future somebody wants to create another collection of widgets, they can call their new collection "AiiDAlab scheduler widgets" , "AiiDAlab metallurgy widgets", ...

P.S. The name of the python package still contains the `_base` suffix, which I won't change now since it is not critical.
We may adapt it in the future (or never).

**Comment by csadorf** [comment]
Yes, the name is a bit "involved", open to changing it, but I would prefer to simply create a new package with much fewer widgets and slightly streamlined API. At the moment I feel like the quality and API of widgets varies greatly. So slowly moving them into a new package with new name would be a way to standardize things. Alternatively we can also just make a version 2.0 of course.

**Comment by ltalirz** [comment]
Thanks for the follow-up, let's discuss it on Monday
