### ISSUE TITLE
pip resolver fails when installing aiidalab-widgets-base

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-widgets-base#228]
Just mentioning that on MacOS with python 3.9.7 `pip install -e .` for aiidalab-widgets-base in my dedicated `aiidalab` conda environment is taking longer than 5 minutes, not sure whether it will finish at all (edit: it also did not succeed in 1h).

The output includes things like
``` 
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
...
INFO: pip is looking at multiple versions of cffi to determine which version is compatible with other requirements. This could take a while.
``` 

How should I install the package for updating the docs?

@csadorf @yakutovicha

**Comment by ltalirz** [comment]
the same has also started happening on readthedocs since August 24th
https://readthedocs.org/projects/aiidalab-widgets-base/builds/

**Comment by csadorf** [comment]
Indeed, looks like the dependency resolution has become too complicated/impossible. We can probably use Pipfile or so, to fix this. @yakutovicha Have you previously observed this issue?

**Comment by ltalirz** [comment]
Forgot to bring this up at the meeting. For my docs changes I resorted to `--use-deprecated=legacy-resolver` but it would be important to fix this. @yakutovicha Coud you have a look into this?

**Comment by yakutovicha** [comment]
> @yakutovicha Have you previously observed this issue?

Not really, but I think it is important to fix that asap. I will take care of that.

**Comment by ltalirz** [comment]
this is the complaints I get when installing with the legacy resolver
```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
jupyter-client 7.0.2 requires nest-asyncio>=1.5, but you'll have nest-asyncio 1.4.3 which is incompatible.
nbconvert 6.1.0 requires traitlets>=5.0, but you'll have traitlets 4.3.3 which is incompatible.
```
