### ISSUE TITLE
jupyter_notebook_url variable

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-widgets-base#235]
Many notebooks in the app contain an undefined `jupyter_notebook_url` (I'm running the notebooks locally using a jupyter notebook server).

@yakutovicha could you please comment?

**Comment by yakutovicha** [comment]
This variable is defined by the appmode, I believe. Did you activate it?

**Comment by yakutovicha** [comment]
If you can get rid of this variable entirely, I wouldn't mind :).

**Comment by ltalirz** [comment]
Thanks for the reply! Indeed I did not install appmode in this environment.

As far as I'm aware, this information is not available from jupyter directly but one can get it quite easily by executing a cell
```
%%javascript
IPython.notebook.kernel.execute('jupyter_notebook_url = "' + window.location.href + '"')
```

Anyhow, I'll just keep this for the record; I think it will be safe to assume that appmode is installed
