### ISSUE TITLE
StructureViewerWidget: the povray rendered ignores the supercell settings.

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-widgets-base#252]
**Describe the bug**

When rendering a structure with pov-ray it ignores the supercell settings.

**Expected behavior**

The pov-rayrendered view should be identical to the in-browser rendered view.

**Screenshots**

**Version (if known)**
 - App version: [e.g. v21.10.0b1]

**Comment by dou-du** [comment]
I just resolved this issue.

**Comment by yakutovicha** [comment]
Thanks, @dou-du!

Just a little suggestion, please always make changes through the PRs. This has several benefits including auto-generation of the release notes.

For the record: this has happened in the commit 7040fc28c772ca53f01c5347d283db3f0fc13cae.
