### ISSUE TITLE
NodesTreeWidget: find outputs not working for nested namespace

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-widgets-base#262]
I have the following outputs with some output nodes collected in the namespace:

```
Outputs                         PK    Type
------------------------------  ----  ------
convergence_cohesive_energy
    output_parameters           8916  Dict
delta_factor
    output_birch_murnaghan_fit  8937  Dict
    output_delta_factor         8943  Dict
    output_volume_energy        8935  Dict
pseudo_info                     7795  Dict
```

It will cause an issue when I want to represent the output as a NodesTreeWidget.
The exceptions is `AttributeError: 'AttributeDict' object has no attribute 'pk'`. 
It is because the `_find_outputs` class method did not detect when the output is a namespace the type `AttributeDict`.

**Comment by danielhollas** [comment]
Oh brilliant, I have just hit this bug, glad that it is already reported. :blush:

**Comment by unkcpz** [comment]
The fix only works for one layer of nest namespace hierarchy of outputs. If the namespace have more namespace it is still broken the work chain node view
