### ISSUE TITLE
Add smiles code to StructureData.extras in SmilesWidget

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-widgets-base#264]
Just a small feature request, I think it would be nice for structures generated from SMILES code to have that info preserved on the StructureData node. I am an aiida noob, but node extras seems to be a good place to put it? I am happy to submit a PR if there is interest in this functionality.

PS: Kudos to the aiida team, have been playing with AiidaLab for a while at it was surprisingly easy to get going thanks to the good documentation and clear code. Thanks! 
(I am working on an AiidaLab app for generating UV/Vis spectra).

**Comment by yakutovicha** [comment]
Thanks @danielhollas!

I quickly asked @cpignedoli who originally created the SMILES widget and he is also in favour of storing this info.

The only question is: should we use attributes or extras for that? Extras can be modified, while attributes can't.

**Comment by danielhollas** [comment]
Thanks all. I am also leaning towards smiles in extras, because then I can set them retroactively even e.g. for structures uploaded from an XYZ file.

Sidenote: I haven't find a good intro to node extras versus attributes in the documentation, but maybe I was not searching long enough.

**Comment by yakutovicha** [comment]
> Sidenote: I haven't find a good intro to node extras versus attributes in the documentation, but maybe I was not searching long enough.

I would say that the main difference is the mutability. Extras can be modified, while attributes can't. There is a bit of information here: https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/data_types.html#creating-a-data-plugin. 

> Each node has attributes that can store any key-value pair, as long as the value is JSON serializable. By adding the value to the node’s attributes, they will be queryable in the database once an instance of the NewData node is stored.

But I agree that it would be a good idea to have a small paragraph that talks specifically about attributes/extras.

**Comment by yakutovicha** [comment]
Alright, it seems that there is a consensus here to put SMILES into extras.



>  I am happy to submit a PR if there is interest in this functionality.

@danielhollas feel free to go ahead then!
