### ISSUE TITLE
SmilesWidget: Canonicalize input SMILES string

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-widgets-base#331]
Since #264 we are storing the input SMILES string in the StructureData extras. However, to make this actually useful, we should canonicalize the smiles string before we store it. 

There are apparently different canonicalization algorithms so we should just pick one that readily available. It should be possible to do with RDKit, per https://ctr.fandom.com/wiki/Convert_a_SMILES_string_to_canonical_SMILES

I will take this on.

**Comment by csadorf** [comment]
Thanks a lot!
