### ISSUE TITLE
support building supercell.

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-widgets-base#365]
Bring up by @superstar54 from https://github.com/aiidalab/aiidalab-widgets-base/pull/327#issuecomment-1275101340

> Cell Transformation is a more general concept. If we use this term, it is better to include the general transformation matrix. > Please have a look at make_supercell method here. 
> https://wiki.fysik.dtu.dk/ase/ase/build/tools.html#ase.build.make_supercell

**Comment by yakutovicha** [comment]
@superstar54, can you take care of this? If yes, please assign yourself.

of course, this can be done only after #327 is merged.

**Comment by unkcpz** [comment]
I have a quick check of the VESTA, I think we can implement a widget that very similar to this matrix transform editor.

<img width="775" alt="image" src="https://user-images.githubusercontent.com/8831685/195422223-becd826a-2e60-4efa-892d-350e19f39b86.png">

**Comment by superstar54** [comment]
> can you take care of this? If yes, please assign yourself.

Sure, I will implement it.
