### ISSUE TITLE
support different model styles for the structure, e.g. Sphere, Ball-and-Stick

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-widgets-base#366]
I am working on it migrating what we did for the empa_viewer, I will need the help of @yakutovicha  to finalize it

**Comment by superstar54** [comment]
Thanks for implementing this. Please assign me as a reviewer when done. I am interested in it.

**Comment by cpignedoli** [comment]
more than happy to have you all @superstar54 @danielhollas on board :) but I can anticipate that what was in empa_viewer was not really performant 
https://github.com/nanotech-empa/aiidalab-empa-surfaces/blob/318670658e7e7d090e9c84dac53626bca8b9a638/widgets/empa_viewer.py#L161
