### ISSUE TITLE
nbconvert version is too strict and other dependencies

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-widgets-base#384]
https://github.com/aiidalab/aiidalab-widgets-base/blob/035047f38f4e92a3b13ecc99879cb4a61fd6cde4/setup.cfg#L33

Hi @yakutovicha, do you remember why this has to be pinned with `nbconvert<6`? I think we can go through the dependencies and polish them.

**Comment by yakutovicha** [comment]
Honestly, I don't. I agree - we should revise the dependencies. It should probably go along with enabling tests.

**Comment by unkcpz** [comment]
This is closed by #395
