### ISSUE TITLE
ASE deprecation warnings

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-widgets-base#387]
As I am now testing my app with deprecation warnings turned on, just reporting this one:

> /opt/conda/lib/python3.9/site-packages/ase/atoms.py:1487: FutureWarning: Please use new API (which will return the angle in degrees): atoms_obj.get_dihedral(a1,a2,a3,a4)*pi/180 instead of atoms_obj.get_dihedral([a1,a2,a3,a4])
  warnings.warn(

**Comment by yakutovicha** [comment]
@danielhollas, is this still a problem?

**Comment by danielhollas** [comment]
This has been solved in #371
