### ISSUE TITLE
Migration ComputationalResourceWidget to AiiDA 2.1

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-widgets-base#393]
See details:
https://github.com/aiidateam/aiida-core/blob/main/CHANGELOG.md#improved-interface-for-creating-codes

Here's the deprecation warnings that I am seeing:

```
/opt/conda/lib/python3.9/site-packages/aiida/orm/nodes/data/code/legacy.py:23: AiidaDeprecationWarning: The `Code` class is deprecated. To create an instance, use the `aiida.orm.nodes.data.code.installed.InstalledCode` or `aiida.orm.nodes.data.code.portable.PortableCode` for a "remote" or "local" code, respectively. If you are using this class to compare type, e.g. in `isinstance`, use `aiida.orm.nodes.data.code.abstract.AbstractCode`. (this will be removed in v3)
  warn_deprecation(
/opt/conda/lib/python3.9/site-packages/aiida/orm/utils/builders/code.py:19: AiidaDeprecationWarning: This module is deprecated. To create a new code instance, simply use the constructor. (this will be removed in v3)
  warn_deprecation('This module is deprecated. To create a new code instance, simply use the constructor.', version=3)
```

I am not an expert on this widget and have limited means of testing it, so leaving this one up to you @yakutovicha or @unkcpz.

Note that this functionality seems to come from version 2.1. But since the AiiDAlab Docker image is on this version already anyway, we might as well skip to support version 2.1 and don't support 2.0. (The current Docker images needs more fixes, so we never had a proper support for 2.0 anyway)

**Comment by unkcpz** [comment]
@danielhollas thanks for mentioning this. I finish this very late yesterday and forget to make it as a PR. https://github.com/aiidalab/aiidalab-widgets-base/pull/394
