### ISSUE TITLE
computer is not a valid UUID

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-widgets-base#405]
When setting the resource using the "quick setup", the "set up code in AiiDA panel" show `'daint-hybrid' is not a valid UUID`.
 I think there are things not updated for the `ComputerDropdrowWidget`.

**Comment by unkcpz** [comment]
Hi @yakutovicha, the issue here is that when using the "quick setup", in set up code step, the computer is a label read from the database, but we have to change the `ComputerDropdownWidget` only accept the UUID as a value. 
I can only think of a way for this `ComputerDropdownWidget` widget we also allowed the value to be UUID of computer or the label, but this makes the API not compatible with other widgets. 
Any idea for this?

**Comment by unkcpz** [comment]
The catch here is that the `ComputerDropdownWidget` show the computers already configured, but when it is used as an embed widget for "Quick setup", only the computer label is read from the database without being setup in the first place therefore no UUID is available.

**Comment by danielhollas** [comment]
Well, I hate to say I told you so but I did. :sweat_smile: Just linking a previous discussion on this.

https://github.com/aiidalab/aiidalab-widgets-base/pull/375#discussion_r1015487770

I don't see much of a downside of supporting the label. 

In the previous discussion, the issue of non-unique labels after importing nodes was mentioned, but in my testing it seemed that codes / computers are automatically re-labeled when imported so I don't think this is an issue.

**Comment by unkcpz** [comment]
> I don't see much of a downside of supporting the label.

It seems a good solution. Let's have a meeting to discuss this with @yakutovicha together early next week. I'll send the doodle.

**Comment by yakutovicha** [comment]
Well, there is an alternative way to implement a utility function. Something like so:

```python
from aiida.common.exceptions import NotExistent
def load_c(label):
    try:
        return load_computer(label)
    except NotExistent:
        print("Does not exist")
```
