### ISSUE TITLE
Bug report: "test computer" raises when verdi command fails

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-widgets-base#418]
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments

In the computer resource widget, one can "test computer" once the computer is setup. Obviously, the underlying verdi command `verdi computer test` can fail. When that happens, we need to pass the error to the UI, but currently the app raises.

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
CalledProcessError                        Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/aiidalab_widgets_base/computational_resources.py in test(self, _)
    924             clear_output()
    925             print(
--> 926                 subprocess.check_output(
    927                     ["verdi", "computer", "test", "--print-traceback", self.label.value]
    928                 ).decode("utf-8")

/opt/conda/lib/python3.9/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    422         kwargs['input'] = empty
    423 
--> 424     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    425                **kwargs).stdout
    426 

/opt/conda/lib/python3.9/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    526         retcode = process.poll()
    527         if check and retcode:
--> 528             raise CalledProcessError(retcode, process.args,
    529                                      output=stdout, stderr=stderr)
    530     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['verdi', 'computer', 'test', '--print-traceback', 'localhost-test']' returned non-zero exit status 2.
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWNty5LgN_RVX53WlaqkvHvttM29bM1knnt2pVCrloii2xGmK5JCU2_LW5NsDAmBb3trHPrwBB8AB1H9snlWI2tnNffPTxhuR
Ti5Mm_s_NiLIUScl0xzU5v4_m-O-02nz02bzX9i3pNHZp-vRza6-q5sdrL5Bfzvc_a_d1tt93VS_dbNN883j54ebL-N886tMN-32
pjncN9v7tr357ctH-N22mx9wtZBnMaiIJmjdi0q6bMCmrZu6hRcQfHJBCgC39bHeFtCILu-Djc07sBJpctErWV1cOMtRaItHW_Fu
lzIEr57J8Ogm9dfX6uiHv7roovtBpVh1IpLhwEJHO1zl9Tkbfqw_1A1BYfqODO4IMGrqtASkKVts1O2YJsMY3mQX7fDUkfZ43-sQ
cce-3hMyuV6hfXwmB_RZVV6kEeE9HQ0D_WyP5HgYnG0reTrpbHwDdm3fw1Wnba_tEGm9pXX0dVdnnvBnSu6sbGQCPiC2WFkNyqog
kgtobINnU0Lb81m87O-iU4Zivq1zWnWQFVIYQ4bingx5F1KsT7OVyTkTKxPmSgo5Krz7iER0Miw-
kW3oYKfEnPRpNtHNfg8L-xzZbHRnFBwG5AAWE6DtWZGlh_wbXBrRrj2ZFVwy2i9o1i2a9TE__9HZFBxZ24AT-
Vm0C83EJ1s0Tq5cJ7ekCmAcUg8VAWXV7gvK7zT4NMcHDD-
gqZDWIapUWcgnYfQrWp35pEU1aXtyfMMdvaSDnCNdeYvMSKPlGYAP5Y38G-rPnvRQnbRRq4qjtei1tfhUtguDKZ1xQUyCU-yAkO0
FOclPZ6DiUq9GYXsgekB3rhvgTdd942AcCUtuDuhDU7AcWzcE4ccM7yDTiddFmmIWpVQvJKgZ5wUBSUgjYlTEQc7QXnXzwA8ckYJ
egfxwth6YzV6d5qj6l8lw3An0QUE4SfxKIvc6nitwA2Q0JtKxQmBvI8kobqeq6Wdz0ZLLcVsf8j41CW2qZ4hpf60aKkkFSbZ4p20
iD7Lj6kUqn40YAmQ3M0ULSkLaM8vkyAmqVHhN7pNIZOhbdDbmlBHkCelCjr9xmB87VpST0emJ5XnHPJwgSm9ZvqONGKBn_VocaxB
TyhqV2J5M9jhPwp6CVpAPGIQtnta9FfhC9kNPueiN7qpJJZGDWCr4_WpQUN5BYnAPdbnJL1DOFrXlmB1jkMNwW-92ayhrFXBm4kp
28hJYzkhLCCs-XnH7J7BSLwkcUv2KeJ1iL-ygIEZx1dq-qZ6C0ZDy_6LtN9Gi67zBgSJ1eBFZk0N14Jo-8G_MCC7_HWNBnchi_n0
N765cNINfKjxBWUNaERd0Y1mgMF-1kvEqqvDMCtncvVtJClqZghRldVg9M84dvr1dg9S-IcpYim9g5ZdhUiXJifO31aerAW2Wwve
L1VtgCvVnfXkT7CMD0ZniBHVPI8IZ9AkUNRQRz5YC-ZOYOsESQT4ZN8xhXlX2Z3F2HKPMP55Y7f8Md_fuYtnZhqHZP4pTmRcaPJe
8yf2l40bfvgMrbUE0FZObPZl0TLMtV2Q3JghaBbIXSkVCXu3RiCkOWX5XAjHNJuley4S1QaliRYpQT3iQGLAdaiYOKEXeM8ZZU7o
gQM4CpZRJJG62y6OlSFiQNLZYFVOFY4Emxg7oiB3Ms1YXTpHMoXVJdc6d0bY9NdSCVXHU0yrH7DxxfFpKYQf9fiw0ki0ONHISPB4
1JFIFq67ecAdu7jZlLiX9bEmuvJiUEUzhloDvnuqOf0Obi-xYy4CToKQQkoLTRuiYGrOmLbmWs8_x-
EavpbGEsQypXgXtcsxEZ0pvaxB_gXE3Yb2Sc36IM9cPXgbN26gIM4PiqGWiHrQxLtN-
VxzQnto2pYg_D1kOn7K2QsE8WTEp7kfY-r1h6uEZqjYfYHpOo5pjtcqRZn9d9KnKTp11KtHGlZjfwUS5I0fjIp0fWiTojlxgKE-
jAkXmupIWuBqkP64y0sNnTKWgja5U5GH5qE__-oo0USp7uDOKxMW8I-SqA3CqIWgOBjN7T8OXX0DOE0_tzZYvv6oWxJT4fFh--fo
FgQP__of4aNaJsPzqlX18_LSehv2SLaDUyxRhOi6AxHRllBrGw_IIHZoy65Ytw0YGfVIxpS1kRPu2krtBBRI2sIfbcsx9k2Lyq7r
KjU9QdKkVA_BKVUL18LD8--fPnzBqHODlFb9t2j1fG3oKNBdWPhTU9xlUgGhqyY2CXWf53N6O64XJsXZxYw8nubv7cMvJmPtHmHN
11ovgKS2PuM17vJYkCjkdjtelKi9VZWTd5qbyIT8RpQbjK_hECPz5uEceAWe5IYceodm3X4KI4-p7DSbz2ZfqPRZ-4gjiOs-6Zw1
pENQv5Bk1k2g1TPpuNfblz5ao1bNipWlr72LCo34o4wGczvn8-M9PP5vc65fS3HAfTL7nimcnGDNrBgOMY4lHGxKhmAKoS5Xp3e3
uqJwABr2ZjUjl6xKLHyQNvjFET5rF1qcxKNF7cFwmw4MM4touMsZ21ZiTK5Gi-
sm_9SolM3uv62YMwzA_R60xfe8nLOUjsQvZqpOh7p8ZxzMLfLAMTziS5f8pItd-Xpv9CbQIC4JTLt8Klf72TcUk7ggHrnfUZ44Uu
t8FTJ_LSp8vIsmxd0PxK1fNRcJQwl_gLQbpojr8aOIxpSVIWenKV3aJEcARMh8-865q2nAufVXh_KrmYTVOXkaliNIdiQFNQ09_7
holKDws2e5Kz-ofhguM8Dyr04MvKU9m5QOGYrSIYFb_XLxq7_nPoe3mx4__A8yCNTo=</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by unkcpz** [comment]
@danielhollas thanks for the reporting, I'll take a look at this.

**Comment by danielhollas** [comment]
I am moving this to a 2.0.1 milestone since this doesn't seem to be a blocker for the 2.0 release.

**Comment by yakutovicha** [comment]
I assume this is already fixed as a part of https://github.com/aiidalab/aiidalab-widgets-base/pull/373. I keep it open until #373 is merged and we get the confirmation that things work as expected.

I moved it to the next milestone `2.1.0`.
