### ISSUE TITLE
Run pytest inside the container

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-widgets-base#443]
In the current testing schema, the AiiDAlab docker container is used to test the behaviour of the widgets. The disadvantage of such an approach is the inability to measure the test coverage.

I propose launching the tests from inside the container. That should simplify the coverage measure.

**Comment by danielhollas** [comment]
@yakutovicha I guess this one can be closed?

**Comment by unkcpz** [comment]
I guess we are not going to move on this route for the moment. I close it for the moment. Feel free to reopen it @yakutovicha

**Comment by yakutovicha** [comment]
yes, all good. Let's close it for the moment.
