### ISSUE TITLE
The exception raised that the interface calling ProcessMonitor Widget is incorrect.

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-widgets-base#456]
The `ProcessFollowerWidget` still using old interface of `ProcessMonitor`.

https://github.com/aiidalab/aiidalab-widgets-base/blob/cc17af7a9e369f4d60a49b2001712d2749f8a333/aiidalab_widgets_base/process.py#L314-L320

**Comment by yakutovicha** [comment]
I think that is fixed in https://github.com/aiidalab/aiidalab-widgets-base/pull/455, could you double-check if the issue persists?

**Comment by unkcpz** [comment]
Thanks, yes this is fixed. :+1:
