### ISSUE TITLE
Enable`StructureUploadWidget` to upload multiple structures.

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-widgets-base#5]
to avoid code duplication

**Comment by yakutovicha** [comment]
With the current status of the things the original implementation of`MutltiStructureUploadWidget` is not really needed. My assumption is that after #31 is merged users will be able to select multiple structures. [The code](https://github.com/aiidalab/aiidalab-widgets-base/blob/develop/aiidalab_widgets_base/structures_multi.py) is still there, but I think I will delete it as soon as I will be able to allow uploading multiple structures through the standard `StructureUploadWidget`: https://github.com/aiidalab/aiidalab-widgets-base/blob/cfd086b2f089fcdb9a04195b9154aab009e1e273/aiidalab_widgets_base/structures.py#L214

**Comment by yakutovicha** [comment]
I think the current functionality covers the most common use cases.
