### ISSUE TITLE
Structure viewer: cell is absent when downloading structure in XYZ format.

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-widgets-base#500]
Until recently, if one downloads XYZ structure, it always contained a cell. Now it is not the case anymore.

We should bring this functionality back and add a test for it.

**Comment by danielhollas** [comment]
@yakutovicha because it was a bit of a breaking change (it changed the public traitlet) I would propose we release this in 2.1. Is that okay for you?

**Comment by yakutovicha** [comment]
> @yakutovicha because it was a bit of a breaking change (it changed the public traitlet) I would propose we release this in 2.1. Is that okay for you?

Yep!
