### ISSUE TITLE
Make optimade dependency optional

### ISSUE THREAD

**Issue by danielhollas** [aiidalab/aiidalab-widgets-base#547]
optimade dependency is quite heavy and is often a source of dependency conficts. 
Since not all apps depend on it, it would be good to make it optional. This will be especially important once we start installing AWB into the aiidalab-docker-stack image. Note that there is a precendence for optional dependency, `rdkit` is only installed when `smiles` dependency group is specified.

Note that this will be a breaking change for apps depending on Optimade (like QeApp) so this needs to be released at least within a minor release.

Relates to #392

**Comment by unkcpz** [comment]
I remove this from the roadmap since it is tracked by #590.

**Comment by danielhollas** [comment]
This was done in #554 but not yet released, so I'll keep this issue open for a bit longer. QeApp will need to be modified when we release AWB 2.2.0

**Comment by danielhollas** [comment]
We've release an alpha version and integrated it to QeApp so I'll close this.
