### ISSUE TITLE
API for structuremanager

### ISSUE THREAD

**Issue by ltalirz** [aiidalab/aiidalab-widgets-base#65]
The current API of the Structuremanager requires the user to know that you have to pass a list of tuples where the first item is the title and the second the importer widget.
These implicit things are not easy to remember and one usually tries to avoid them in APIs.

One way to avoid this would be this:
```
StructureManager(importers=[ Importer1(title="asdfasf"), Importer2(title="sfesdf"), ...])
```

It also lets you set a default title if people don't need a specific one.

**Comment by yakutovicha** [comment]
I agree with @ltalirz - this approach seems to be a better one. I will make a PR with an aim to finalize the API of structure manager.
