### ISSUE TITLE
Check if structure already present in datadase

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-widgets-base#7]
A useful check when uploading a structure would be to prompt the user if the structure being uploaded is "similar" (or "identical" ?) to a structure already present.
The user can then decide whether to proceed or not with the upload.

Example of such a check can be found following [this link](https://github.com/cpignedoli/aiidalab-empa-surfaces/blob/833890df5f078228429d771332c629d83ad35415/upload_structure.ipynb#L69)

were structures with same chemical formula are identified

**Comment by ltalirz** [comment]
Definitely makes sense.
For "identical" one should check the node hash.
For "similar" one can indeed check the formula (but this may not be available for all structures, e.g. cif)
