### ISSUE TITLE
Temporary file path exposed in StructureUploadWidget

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-widgets-base#71]
Is there a reason that we expose the file path of a temporary file as a traitlet?

https://github.com/aiidalab/aiidalab-widgets-base/blob/e9b11c54e62a0f37cfa78314c6e7d1e77426abd6/aiidalab_widgets_base/structures.py#L218

It seems to me that this is completely unnecessary and has the additional disadvantage that we would need to tie the lifetime of the temporary file to the widget lifetime.

As a related issue: As far as I can tell, the temporary file is not removed at all currently.

**Comment by danielhollas** [comment]
The widget has been refactored significantly since this issue was created so this can be closed.
