### ISSUE TITLE
Sorting files in structures_multy.py

### ISSUE THREAD

**Issue by eimrek** [aiidalab/aiidalab-widgets-base#8]
It would be very convenient if files were uploaded in alphabetical order
https://github.com/aiidalab/aiidalab-widgets-base/blob/59b4caf5831f25998479b4be67a480f9643855ed/aiidalab_widgets_base/structures_multi.py#L123

**Comment by ltalirz** [comment]
I believe you'll be able to make a PR for that ;)

**Comment by eimrek** [comment]
Sorry Leopold, this issue was created by mistake.
