### ISSUE TITLE
Replace COM with geometric center

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-widgets-base#96]
https://github.com/aiidalab/aiidalab-widgets-base/blob/791d88b2d0b2108d00aeea8b79b55b0891616793/aiidalab_widgets_base/structures.py#L660

here we should have:
np.average(self.structure[self.selection].get_positions(), axis=0)

**Comment by yakutovicha** [comment]
thanks for the report, @cpignedoli can you make a PR for that?
